### PR TITLE
Exclude MDN (Mozilla Dev Network)

### PR DESCRIPTION
**Pull request by davidfischer**
Ref #14

### CODE REVIEW

**Review by ericholscher — APPROVED** [review]

**Comment by metametapod** [comment]
Thank you for adding this! Are there blockers to getting it merged?

**Comment by ericholscher** [comment]
Think it just got forgotten. I'll go ahead and merge it now 👍

**Comment by metametapod** [comment]
FWIW I don't see this yet on https://ads-for-open-source.readthedocs.io/en/latest/_static/lists/opensource-ads.txt

**Comment by davidfischer** [comment]
The [build failed](https://readthedocs.org/projects/ads-for-open-source/builds/23914664/). It looks like this repository hasn't been updated much and it needs a RTD configuration file. I'll get to it next week.

**Comment by davidfischer** [comment]
This is now out!

**Pull request merged**
